dist: xenial
sudo: required
language: node_js
node_js:
  - "8.11.3"

cache:
  directories:
    - "node_modules"

before_install:
  - npm i -g ganache-cli@6.1.0 truffle@4.1.8
  - ganache-cli &>/dev/null &

install:
  - npm i
  - npm run setup
  - npm run start:auth &
  - npm run start:proxy &
  - npm run start:server &
  - npm run start:client